name: Build

on:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
          cache-dependency-path: poetry.lock
      - name: Set Poetry environment
        run: |
          poetry env use ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          poetry install --no-root
      - run: poetry run pyinstaller --add-data "static/icon.png:static" main.py
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: main
          path: dist/
